#+TITLE: 幸福的距离
#+AUTHOR: zhxchen17
#+DATE: 2018-09-20

#+HUGO_BASE_DIR: ../blog/

#+HUGO_SECTION: posts
#+HUGO_TAGS: single toml

#+HUGO_DRAFT: false

对于一个对身边的世界很迟钝的人来说，当世界显露出来它真实面貌的时候，这种错位感就像突然跳进了游泳池，只能感觉到突如其来寒冷。
但是世界并不会一下显露出它真实的面貌，生活总是在一点一点地泄露这些细微而又让人沮丧的事实。

我是一个即使读了研究生也时不时觉得自己十分中二的人，有时候还会得到别人善意的嘲讽。从我的记忆里，很久很久之前我就
相信这个世界的一些基本的规律，那就是好事和坏事总是交替出现，得到任何一件自己想拥有的东西都要给予对等的努力和代价。
直到一个夏天，突然意识到深信着这些东西的我，其实并没有完全贯彻这些信念，相信愿意相信的东西只是为了让自己感到心安理得，
而这个世界也似乎第一次向我展示了它真实的一角，第一次体会到当别人都在没关系，但是只有自己明白一切的报应都来源于，
我没有付出足够的努力来对抗现实，所以也第一次感受到“幸福”是“能贯彻自己相信的东西”。

接下来的几年里，为了把自己从更多的后悔中挽救出来，付出了几乎所有自己作为普通人能承受的努力。如果说过去的十年里面
哪个时刻我最远离“幸福”，那我肯定会说是某个夏天，但是如果说哪个时刻我最接近“信服”，我还是觉得会是现在。在从最“不幸福”
到局部最“幸福”的过程里，超过了讨厌的那个自己，把全部的否定都如数奉还，战胜了那些自以为是的人，这些东西从某个时刻
开始就成为了攀登的目标。

在自以为接近“幸福”的道路上，到头才发现进度刚刚完成了1%。

对于普通人来说，“幸福”更像是一种调和自己和现实的结果。世界上再也出现不了有趣的人，那就让自己也变无趣，世界上再也出现
不了有趣的事情，那就让自己也变简单。从以前，到现在，一直都想保持自己的独一无二，但是最后会渐渐发现这样的人注定会自绝
于大众，走向越来越孤独的道路。

仍然，我觉得有时候因为提前支付了人品，生活里幸运的事情还是能一件一件地出现，有支持自己的父母，找到了无法替代的人，有
一些N年都能聊得来的朋友，很快能得到一份支持生活的工作，得到了几乎大部分想得到的知识，在芸芸大众当中已经得到了与努
力程度不相称的过多东西。仍然，没有感到足够的“幸福”，因为现实是

有趣的事出现的越来越少，都是金钱地位。

有趣的人出现的越来越少，都是陈词滥调。

也许像麦田里的守望者里那样，把眼睛遮蔽，把耳朵堵住，把嘴巴紧闭，才能让自己变“幸福”，但是接下的生活已经不可能让我像
高中生一样用这种躲避的方式活着。

对于活在未来的人来说，“未来”永远存在着纯粹的理想，“现在”永远是枯燥的现实。对于活在当下的人来说，“未来”是捉摸不定的
变量，“现在”才存在着可以把握的“幸福”。每次看着能把握自己眼前那点幸福的人，我总是怀着羡慕而又嫉妒的心情，因为我知道
这种东西是我不可能做到的。

也许当能不再在意其他普通人的眼光，能得到一小部分人的承认，能实现一小部分自己的愿望，能在不伤害别人的情况下相信和贯彻
自己的原则，至少对我来说离幸福的距离就更近了吧。
